version: "3.5"

services:
    broker:
        container_name: broker
        image: eclipse-mosquitto:latest
        ports: 
            - "1883:1883"
            - "9001:9001"
        volumes: 
            - "./volumes/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
            - "./volumes/mosquitto/data:/mosquitto/data"
            - "./volumes/mosquitto/log:/mosquitto/log"